### ISSUE TITLE
CLI entrypoint

### ISSUE THREAD

**Issue by ostrolucky** [gnugat/nomo-spaco#7]
Would be nice to have some CLI file in bin folder, so I can just install this project and use it, instead of having to write code. I guess only one argument is needed (path), so should be simple enough

**Comment by gnugat** [comment]
You can use the following provided scripts:

```
php ./test/findAll.php <projectRoot>
php ./test/findOne.php <projectRoot> <classname>
```

**Comment by ostrolucky** [comment]
Ahh, fair enough!

**Comment by ostrolucky** [comment]
Although, ideally this should be configured as bin in composer.json, so I can install and execute this via composer (instead of manually locating location of test directory)

**Comment by gnugat** [comment]
That's a good idea! Would you mind creating a Pull Request for this?

**Comment by ostrolucky** [comment]
See https://github.com/gnugat/nomo-spaco/pull/8

**Comment by ostrolucky** [comment]
Ping @gnugat You asked me to work on this patch, hopefully my work doesn't go to waste.
